import { Client, Variables, logger } from 'camunda-external-task-client-js'
import chalk from 'chalk';

const config = {
    baseUrl: 'http://localhost:8080/engine-rest',
    asyncResponseTimeout: 10000,
    use: logger,
};
const client = new Client(config);

console.log(chalk.yellow.bold("üîÑ Iniciando Worker de verificaci√≥n de pago..."));

client.subscribe("verificar-pago", { lockDuration: 10000 }, async function({ task, taskService }) {
    try {
        const valorIngresado = task.variables.get("pagoIngresado");
        const costoReal = task.variables.get("valorRealAPagar");

        let pagoValido = valorIngresado >= costoReal;
        let saldoSobrante = pagoValido ? valorIngresado - costoReal : 0;

        const processVariables = new Variables()
            .set("pagoValido", pagoValido)
            .set("saldoSobrante", saldoSobrante);

        console.log(chalk.blue.bold("\n=== Verificaci√≥n de Pago ==="));
        console.log(`${chalk.cyan("Valor ingresado:")} $${valorIngresado}`);
        console.log(`${chalk.cyan("Valor esperado: ")} $${costoReal}`);

        if (pagoValido) {
            console.log(chalk.green.bold("‚úÖ Resultado: PAGADO"));
            if (saldoSobrante > 0) {
                console.log(chalk.green(`üí∞ Saldo sobrante: $${saldoSobrante}`));
            }
        } else {
            console.log(chalk.red.bold("‚ùå Resultado: RECHAZADO"));
            console.log(chalk.red("Monto insuficiente!"));
        }

        await taskService.complete(task, processVariables);

    } catch (error) {
        console.error(chalk.red("‚ö†Ô∏è Error en la tarea de verificaci√≥n de pago:"), error.message);
        await taskService.handleFailure(task, {
            errorMessage: "Error en verificaci√≥n de pago",
            errorDetails: error.message,
            retries: 0,
            retryTimeout: 1000
        });
    }
});
